rastro/src/main/java/com/rasz/bean/UsuarioCriteria.java
package com.rasz.bean;

import java.util.ArrayList;
import java.util.List;

import org.primefaces.event.SelectEvent;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.webflow.engine.RequestControlContext;
import org.springframework.webflow.execution.Event;
import org.springframework.webflow.execution.RequestContext;
import org.springframework.webflow.execution.RequestContextHolder;

import com.rasz.domain.FlowRuleEnum;
import com.rasz.domain.Usuario;
import com.rasz.repository.UsuarioRepository;
import com.rasz.utils.FlowUtilsFactory;
import com.rasz.utils.Utils;

public class UsuarioCriteria extends AbstractCriteria<Usuario> {

	private static final long serialVersionUID = 1L;
	
	@Autowired private transient UsuarioRepository usuarioRepository;
	
	private Usuario usuario;
	private Boolean ativo;	
	private String nome;
	private String login;
	private String email;
	private Integer code;
	
	@Override
	public Page<Usuario> load(Pageable pageable) {
		Authentication auth = SecurityContextHolder.getContext().getAuthentication();
		if (auth != null) {	
			return usuarioRepository.listarTodos(nome, login, email, code, ativo, pageable);		
		}else{
			return null;
		}
	}
	
	public void someListenerSelecionarUsuario(SelectEvent event){
		if(!Utils.isMobileDevice())
			return;
		
		if(event != null){
			usuario  = (Usuario) event.getObject();
			RequestContext requestContext = RequestContextHolder.getRequestContext();
			RequestControlContext rec = (RequestControlContext) requestContext;
			rec.handleEvent(new Event(this, "listarProdutos"));
			FlowUtilsFactory.currentInstance(FlowRuleEnum.FLOW_SCOPE).put("usuario", usuario);
		}
	}
	
	public Usuario retornausuario(){
		return usuarioRepository.findOne(((Usuario) this.usuario).getId());
	}
	
	@Override
    public Object getRowKey(Usuario usuario) {
        return usuario != null ? usuario.getId() : null;
    }

    @Override
    public Usuario getRowData(String rowKey) {
		List<Usuario> list = (List<Usuario>) getWrappedData();

        for (Usuario p : list) {
            if (p.getId().toString().equals(rowKey)) {
                return p;
            }
        }

        return null;
    }
    
    public List<String> complete(String busca) {
		List<String> resultados = new ArrayList<String>();
		for (Usuario o : usuarioRepository.findAll()) {
			if ((o.getNmUsuario().toLowerCase().concat(" - ").concat(o.getLogin().toLowerCase())).contains(busca.toLowerCase())) {
    			resultados.add(o.toString());
			}
		}
		return resultados;
	}
    
    public void limparCampos() {
    	ativo = null;
    	nome = new String();
    	login = new String();
    	email = new String();
    	code = null;
    	usuario = null;
    }
    
    public Usuario getUsuario() {
		return usuario;
	}


	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}


	public String getNome() {
		return nome;
	}


	public void setNome(String nome) {
		this.nome = nome;
	}

	public Boolean getAtivo() {
		return ativo;
	}

	public void setAtivo(Boolean ativo) {
		this.ativo = ativo;
	}

	public String getDescricao() {
		return nome;
	}

	public void setDescricao(String nome) {
		this.nome = nome;
	}
	
	public String getLogin() {
		return login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Integer getCode() {
		return code;
	}

	public void setCode(Integer code) {
		this.code = code;
	}

}

rastro/src/main/webapp/WEB-INF/flows/cad_usuario/edit.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	    		xmlns:ui="http://java.sun.com/jsf/facelets"
	  			xmlns:h="http://java.sun.com/jsf/html"				
	  			xmlns:f="http://java.sun.com/jsf/core"
	  			xmlns:p="http://primefaces.org/ui"
				template="/WEB-INF/templates/template.xhtml"
	  			xmlns:campo="http://java.sun.com/jsf/composite/components/campo">
			

<ui:define name="title">User</ui:define>

<ui:define name="content">
<div class="span-10">
	<h:form id="form" onkeypress="if (event.keyCode == 13) return false;">
		<p:growl id="msgs" showDetail="true" showSummary="false" life="2000"/>
		<div class="row">	
			<div class="col-md-12" style="border: none !important;">
				<p:panel header="USER DETAILS" style="border: none !important;">
					<p:fieldset id="plCadastro" style="border: none !important;">
						<div class="row" style="border: none !important;" >
							<div class="col-md-12">
								<p:selectOneButton label="Active?" value="#{usuarioService.usuario.boAtivo}" disabled="#{!usuarioService.permissaoSalvar}">
						            <f:selectItem itemLabel="Active" itemValue="true"/>
						            <f:selectItem itemLabel="Inactive" itemValue="false"/>
						        </p:selectOneButton>
							</div>
						</div>	
						
						<div class="row">
							<div class="col-md-6">
								<campo:simples label="Name" value="#{usuarioService.usuario.nmUsuario}" required="true" disabled="#{!usuarioService.permissaoSalvar}"/>
							</div>	
								
							<div class="col-md-6">	
								<div class="input-group" style="width: 100%">
									<campo:simples label="Username" value="#{usuarioService.usuario.login}" required="true"
												   disabled="#{!usuarioService.permissaoSalvar}" transform="none">
									</campo:simples>
									
									<div id="btnUserFound" class="input-group-btn" style="vertical-align: bottom; margin:0; padding-bottom:0px; padding-left:-5px">
										<p:commandButton disabled="true" rendered="#{usuarioService.disabledUserNotFound}" icon="imagemconfirmar" styleClass="ui-button-success" style="width: 30px"/>
					                    <p:commandButton disabled="true" rendered="#{usuarioService.disabledUserFound}" icon="imagemexcluir" styleClass="ui-button-danger" style="width: 30px"/>
								 	</div>
								 </div>
							</div>
						</div>
						
						<div class="row">
							<div class="col-md-12">	
								<div class="row" >
									<div class="col-md-6"> 
								        <p:outputLabel for="pwd1" value="Password" rendered="#{usuarioService.renderedPassword}"
								        	style="width: 100%" disabled="#{!usuarioService.permissaoSalvar}"/>
								        			   
 								        <p:password id="pwd1" value="#{usuarioService.usuario.senha}" match="pwd2"
		 								        	toggleMask="true" redisplay="true" feedback="true" 
										            weakLabel="Weak" goodLabel="Good" strongLabel="Strong" 
		 								        	required="true" style="width: 100% !important" 
		 								        	validatorMessage="Password should match with Confirm Password."
		 								        	requiredMessage="Password: Required." rendered="#{usuarioService.renderedPassword}"
		 								        	disabled="#{!usuarioService.permissaoSalvar}">
 								        	<p:ajax event="blur" process="@this" />	    
 								        </p:password>
								 	</div>
								   
								    <div class="col-md-6">
								        <p:outputLabel for="pwd2" value="Confirm Password" rendered="#{usuarioService.renderedPassword}"
								         	style="width: 100%" disabled="#{!usuarioService.permissaoSalvar}"/>
								         			   
								        <p:password id="pwd2" value="#{usuarioService.usuario.senha}" 
										        	required="true" feedback="true" 
										            weakLabel="Weak" goodLabel="Good" strongLabel="Strong"
										        	style="width: 100% !important" rendered="#{usuarioService.renderedPassword}"
										        	validatorMessage="Password should match with Confirm Password."
										        	requiredMessage="Confirm Password: Required."
										        	disabled="#{!usuarioService.permissaoSalvar}" >
								        	<p:ajax event="blur" process="@this" />
								        </p:password>
								    </div>
							     </div>	
							</div>
						</div>	
						
						<div class="row">
							<div class="col-md-12">
								<div class="input-group" style="width: 100%">
									<campo:simples label="E-mail" value="#{usuarioService.usuario.email}" 
										required="true" transform="lowercase" disabled="#{!usuarioService.permissaoSalvar}">
									</campo:simples>
									
									<div id="btnEmailFound" class="input-group-btn" style="vertical-align: bottom; margin:0; padding-bottom:0px; padding-left:-5px">
										<p:commandButton disabled="true" rendered="#{usuarioService.emailNotFound}" icon="imagemconfirmar" styleClass="ui-button-success" style="width: 30px"/>
					                    <p:commandButton disabled="true" rendered="#{usuarioService.emailFound}" icon="imagemexcluir" styleClass="ui-button-danger" style="width: 30px"/>
								 	</div>
								 </div>
							
								
							</div>
						</div>
						
						
						<div class="row" align="center" style="margin-top: 10px;  margin-left: 2px">
							<div class="col-md-12">
								<p:commandButton value="Back" action="cancelar" style="width:100px" immediate="true" icon="imagemvoltar"/>

								<p:spacer width="10"/>
								
								<p:commandButton id="buttonSalvar" value="Save" action="salvar" immediate="false" 
										 disabled="#{!usuarioService.permissaoSalvar or !request.isUserInRole('ROLE_CAD_USUARIO_INCLUIR')}"
										 style="width:100px" process="@form" update="@form" icon="imagemsalvar"/>										 	
							</div>
						</div>		
					</p:fieldset>	
				</p:panel>
			</div>
		</div>
	</h:form>
</div>
</ui:define>
</ui:composition>

rastro/src/main/webapp/WEB-INF/flows/cad_usuario/list.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	    		xmlns:ui="http://java.sun.com/jsf/facelets"
	  			xmlns:h="http://java.sun.com/jsf/html"				
	  			xmlns:f="http://java.sun.com/jsf/core"
	  			xmlns:p="http://primefaces.org/ui"
				template="/WEB-INF/templates/template.xhtml"
	  			xmlns:campo="http://java.sun.com/jsf/composite/components/campo">
			

<ui:define name="title">User</ui:define>

<ui:define name="content">
<div class="span-10">
	<h:form id="form" onkeypress="if (event.keyCode == 13) return false;">
		<p:growl id="msgs" showDetail="true"/>
			
		<div class="row" >
			<div class="col-md-12">
				<p:panel header="USER" style="border: none !important;">
					<div class="row">
						<div class="col-md-12">
							<div class="row">
								<div class="col-md-2">															 
									<campo:valor decimalPlaces="0" thousandSeparator="" value="#{criteria.code}" label="Code">
										<p:ajax event="blur" process="@this" update=":form:paneltbl" />
									</campo:valor>
								</div>
							
								<div class="col-md-6">															 
									<campo:simples value="#{criteria.descricao}" label="Name">
										<p:ajax event="blur" process="@this" update=":form:paneltbl" />
									</campo:simples>
								</div>
								
								<div class="col-md-4" style="padding-top: 20px">
									<p:selectOneButton label="Active?" value="#{criteria.ativo}">
							            <f:selectItem itemLabel="Active" itemValue="true"/>
							            <f:selectItem itemLabel="Inactive" itemValue="false"/>
							            <f:selectItem itemLabel="All" itemValue="#{criteria.setAtivo(null)}"/>
							            
							            <p:ajax event="change" process="@this" update=":form:tbl" />
							        </p:selectOneButton>
								</div>
							</div>
							
							<div class="row">
								<div class="col-md-4">															 
									<campo:simples label="Username" value="#{criteria.login}" width="100%">
										<p:ajax event="blur" process="@this" update=":form:paneltbl"/>
									</campo:simples>
								</div>
								<div class="col-md-4" style="padding-bottom: 15px">												
									<campo:simples label="Email" value="#{criteria.email}" width="100%">
										<p:ajax event="blur" process="@this" update=":form:paneltbl"/>
									</campo:simples>
								</div>
								<div class="col-md-4" style="padding-top: 18px">
									 <p:toolbarGroup align="left">
									 	<p:commandButton  icon="imagemfiltrar" title="Search" value="Search" style="width:100px">
											<p:ajax event="click" process="@this" update=":form:tbl"/>
										</p:commandButton>
										
										<p:commandButton icon="imagemlimpar" title="Clean" value="Clean" action="limpar" style="width:100px">
											<p:ajax event="click" process="@this" update=":form:tbl"/>
										</p:commandButton>
									 </p:toolbarGroup>
								</div>
							</div>
						</div>
						
						
						<div class="row" style="margin-top: 15px">
							<div class="col-md-12" >
								<h:panelGroup id="paneltbl">	
										<p:dataTable id="tbl" 
													 value="#{criteria}" 
													 var="item" 
													 paginator="true" 
													 rows="5" 
													 scrollable="true"
           									         scrollHeight="#{criteria.getPageSize() > 5 ? 200 : criteria.getPageSize() == 0 ? 40 : criteria.getPageSize() * 40}"
           									         rowsPerPageTemplate="5,10,15,20,30,50"
													 lazy="true"
													 paginatorTemplate="{RowsPerPageDropdown} {CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink}"
													 emptyMessage="There are no records" 
													 paginatorPosition="bottom" 
													 selectionMode="single"
													 styleClass="tabelaMobile"
													 rowKey="#{item.id}"
													 sortBy="#{item.id}"
													 sortOrder="DESCENDING"
													 resizableColumns="true"
													 currentPageReportTemplate="Page {currentPage} of {totalPages} || {startRecord} - {endRecord} of {totalRecords}">		 
							            	
						            	<p:ajax event="rowSelect" process="@this, tbl" update="tbl"
												listener="#{criteria.someListenerSelecionarUsuario}"/>
												
										<p:column headerText="Code" style="text-align: left; width: 10%" sortBy="#{item.id}">
								             <h:outputText value="#{item.id}" style="white-space:nowrap !important;"/>		            	
								        </p:column>			
												
							            <p:column headerText="Name" style="text-align: left; width: 40%" sortBy="#{item.nmUsuario}">
								             <h:outputText value="#{item.nmUsuario}" style="white-space:nowrap !important;"/>		            	
								        </p:column>	
								        
								        <p:column headerText="Username" style="text-align: left; width: 30%" sortBy="#{item.login}">
								             <h:outputText value="#{item.login}" style="white-space:nowrap !important;"/>			            	
								        </p:column>	
								        
								        <p:column headerText="Email" style="text-align: left; width: 30%" sortBy="#{item.email}">
								             <h:outputText value="#{item.email}" style="white-space:nowrap !important;"/>			            	
								        </p:column>
								        
								        <p:column headerText="Active?" style="text-align: left; width: 30%" sortBy="#{item.boAtivo}">
								             <h:outputText value="#{item.boAtivo ? 'Yes' : 'Not'}" style="white-space:nowrap !important;"/>			            	
								        </p:column>				
														        	
								        <p:column style="width: 150px" >
											<p:growl id="message" showDetail="true" sticky="true" />
							 			    
						 			    	<p:commandButton id="buttonConsultar" action="consultar" update="@form" immediate="true" 
														icon="imagemfiltrar" title="Consult" disabled="#{!request.isUserInRole('ROLE_CAD_USUARIO_CONSULTAR')}">
												<f:setPropertyActionListener value="#{item}" target="#{criteria.selected}" />
											</p:commandButton>
							 			    
							 			    
							 			    <p:commandButton action="editar" disabled="#{!request.isUserInRole('ROLE_CAD_USUARIO_ALTERAR')}"
											 			    id="iconEditar" update="@form" icon="imagemeditar" title="Edit">
							 			    	<f:setPropertyActionListener target="#{criteria.selected}" value="#{item}"/>
							 			    </p:commandButton>
							 			    				 
										    <p:commandButton action="inativar" disabled="#{!request.isUserInRole('ROLE_CAD_USUARIO_REMOVER')}"
										   					 update="message" icon="imagemexcluircampo" title="Inactivate" rendered="#{item.boAtivo}">
										        <p:confirm header="Confirm" message="Are you sure you want to disable this user?" icon="imagemalerta" />
										        <f:setPropertyActionListener target="#{criteria.selected}" value="#{item}"/>
										    </p:commandButton>
										    
										    <p:commandButton action="ativar" disabled="#{!request.isUserInRole('ROLE_CAD_USUARIO_REMOVER')}"
										   					 update="message" icon="imagemgreen" title="Activate" rendered="#{!item.boAtivo}">
										        <p:confirm header="Confirm" message="Are you sure you want to activate this user?" icon="imagemalerta" />
										        <f:setPropertyActionListener target="#{criteria.selected}" value="#{item}"/>
										    </p:commandButton>
										 
										    <p:confirmDialog global="true" showEffect="fade" hideEffect="explode">
										        <p:spacer width="100" height="10" />
										        <p:commandButton value="Yes" type="button" styleClass="ui-confirmdialog-yes" icon="imagempositive" />
										        <p:commandButton value="No" type="button" styleClass="ui-confirmdialog-no" icon="imagemnegative" />
										    </p:confirmDialog>
										    
										</p:column>	
								       	
									</p:dataTable>
								</h:panelGroup>
								
								<p:spacer height="10"/>
								
								<div class="row" align="center">
									<p:commandButton id="buttonNovo" action="novo" value="New" style="width:100px" icon="imagemadicionar" 
													process="@this" update="@form" disabled="#{!request.isUserInRole('ROLE_CAD_USUARIO_INCLUIR')}"/>
													
									<p:spacer height="10"/>				

									<p:commandButton id="buttonVoltar" action="voltarhome" value="Home" style="width:100px" icon="iconehome" />
								</div>
								
							</div>
						</div>
					</div>
				</p:panel>
			</div>
		</div>
			
	</h:form>
</div>
</ui:define>
</ui:composition>